/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OrderEmployeeIdRouteImport } from './routes/order.$employeeId'
import { Route as EmployeesCompanyIdRouteImport } from './routes/employees.$companyId'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderEmployeeIdRoute = OrderEmployeeIdRouteImport.update({
  id: '/order/$employeeId',
  path: '/order/$employeeId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesCompanyIdRoute = EmployeesCompanyIdRouteImport.update({
  id: '/employees/$companyId',
  path: '/employees/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/employees/$companyId': typeof EmployeesCompanyIdRoute
  '/order/$employeeId': typeof OrderEmployeeIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/employees/$companyId': typeof EmployeesCompanyIdRoute
  '/order/$employeeId': typeof OrderEmployeeIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/employees/$companyId': typeof EmployeesCompanyIdRoute
  '/order/$employeeId': typeof OrderEmployeeIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/login'
    | '/employees/$companyId'
    | '/order/$employeeId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/employees/$companyId'
    | '/order/$employeeId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin/login'
    | '/employees/$companyId'
    | '/order/$employeeId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  EmployeesCompanyIdRoute: typeof EmployeesCompanyIdRoute
  OrderEmployeeIdRoute: typeof OrderEmployeeIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$employeeId': {
      id: '/order/$employeeId'
      path: '/order/$employeeId'
      fullPath: '/order/$employeeId'
      preLoaderRoute: typeof OrderEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/$companyId': {
      id: '/employees/$companyId'
      path: '/employees/$companyId'
      fullPath: '/employees/$companyId'
      preLoaderRoute: typeof EmployeesCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  EmployeesCompanyIdRoute: EmployeesCompanyIdRoute,
  OrderEmployeeIdRoute: OrderEmployeeIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
